# Generated by Django 4.1.3 on 2022-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='standup',
            fields=[
                ('date_added', models.DateTimeField(verbose_name='date published')),
                ('employee_id', models.CharField(max_length=200, primary_key='True', serialize=False)),
                ('employee_name', models.CharField(max_length=300)),
                ('work_done', models.CharField(max_length=300)),
                ('work_to_do', models.CharField(max_length=300)),
                ('issues_faced', models.CharField(max_length=300)),
            ],
        ),
    ]
